logging.level.root=INFO
logging.level.com.example.backend=INFO
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never
logging.structured.format.console=logstash
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
